AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.10
    Timeout: 30

Resources:

  NetworkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: network-resources
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: vpc_id
          AttributeType: S
      KeySchema:
        - AttributeName: vpc_id
          KeyType: HASH

  NetworkApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  NetworkFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: src/

      Environment:
        Variables:
          TABLE_NAME: network-resources

      Policies:
        - AmazonEC2FullAccess

        - DynamoDBCrudPolicy:
            TableName: network-resources

      Events:

        RootApi:
          Type: Api
          Properties:
            RestApiId: !Ref NetworkApi
            Path: /
            Method: ANY

        ProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref NetworkApi
            Path: /{proxy+}
            Method: ANY

Outputs:

  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${NetworkApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"